// components/workspace/EditorArea/constants.tsx
import {
  Heading1, Heading2, Heading3, List, ListOrdered, ListTodo,
  Quote, Code, Table as TableIcon, CheckCircle2, Sigma,
} from 'lucide-react';

// ---------- FONT FAMILIES ----------
export const FONT_FAMILIES = [
  { value: 'Inter, sans-serif', label: 'Inter', preview: 'Aa' },
  { value: 'Georgia, serif', label: 'Georgia', preview: 'Aa' },
  { value: 'Times New Roman, serif', label: 'Times', preview: 'Aa' },
  { value: 'Arial, sans-serif', label: 'Arial', preview: 'Aa' },
  { value: 'Helvetica, sans-serif', label: 'Helvetica', preview: 'Aa' },
  { value: 'Courier New, monospace', label: 'Courier', preview: 'Aa' },
  { value: 'Fira Code, monospace', label: 'Fira Code', preview: '</>' },
  { value: 'Playfair Display, serif', label: 'Playfair', preview: 'Aa' },
  { value: 'Roboto, sans-serif', label: 'Roboto', preview: 'Aa' },
  { value: 'Merriweather, serif', label: 'Merriweather', preview: 'Aa' },
  { value: 'system-ui, sans-serif', label: 'System', preview: 'Aa' },
];

// ---------- FONT SIZES ----------
export const FONT_SIZES = [
  { value: '12px', label: '12px', size: 12 },
  { value: '14px', label: '14px', size: 14 },
  { value: '16px', label: '16px', size: 16 },
  { value: '18px', label: '18px', size: 18 },
  { value: '20px', label: '20px', size: 20 },
  { value: '24px', label: '24px', size: 24 },
  { value: '30px', label: '30px', size: 30 },
  { value: '36px', label: '36px', size: 36 },
  { value: '48px', label: '48px', size: 48 },
  { value: '60px', label: '60px', size: 60 },
];

// ---------- PRESET COLORS ----------
export const PRESET_COLORS = [
  { color: '#ef4444', label: 'Red' },
  { color: '#f97316', label: 'Orange' },
  { color: '#f59e0b', label: 'Amber' },
  { color: '#eab308', label: 'Yellow' },
  { color: '#84cc16', label: 'Lime' },
  { color: '#22c55e', label: 'Green' },
  { color: '#10b981', label: 'Emerald' },
  { color: '#14b8a6', label: 'Teal' },
  { color: '#06b6d4', label: 'Cyan' },
  { color: '#0ea5e9', label: 'Sky' },
  { color: '#3b82f6', label: 'Blue' },
  { color: '#6366f1', label: 'Indigo' },
  { color: '#8b5cf6', label: 'Violet' },
  { color: '#a855f7', label: 'Purple' },
  { color: '#d946ef', label: 'Fuchsia' },
  { color: '#ec4899', label: 'Pink' },
  { color: '#f43f5e', label: 'Rose' },
  { color: '#64748b', label: 'Slate' },
  { color: '#78716c', label: 'Stone' },
  { color: '#1e293b', label: 'Dark' },
  { color: '#ffffff', label: 'White' },
  { color: '#000000', label: 'Black' },
];

// ---------- HIGHLIGHT COLORS ----------
export const HIGHLIGHT_COLORS = [
  { color: '#fef08a', label: 'Yellow' },
  { color: '#bbf7d0', label: 'Green' },
  { color: '#bfdbfe', label: 'Blue' },
  { color: '#fecaca', label: 'Red' },
  { color: '#e9d5ff', label: 'Purple' },
  { color: '#fed7aa', label: 'Orange' },
  { color: '#f0abfc', label: 'Pink' },
  { color: '#a5f3fc', label: 'Cyan' },
  { color: '#fde047', label: 'Gold' },
  { color: '#d1fae5', label: 'Mint' },
  { color: '#fef3c7', label: 'Light Yellow' },
  { color: '#dbeafe', label: 'Light Blue' },
  { color: '#fce7f3', label: 'Light Pink' },
  { color: '#f3e8ff', label: 'Light Purple' },
  { color: '#ffedd5', label: 'Light Orange' },
];

// ---------- MATH SYMBOLS ----------
export const MATH_SYMBOLS = {
  'Greek Letters': [
    { sym: 'α', latex: '\\alpha', name: 'alpha' },
    { sym: 'β', latex: '\\beta', name: 'beta' },
    { sym: 'γ', latex: '\\gamma', name: 'gamma' },
    { sym: 'δ', latex: '\\delta', name: 'delta' },
    { sym: 'ε', latex: '\\epsilon', name: 'epsilon' },
    { sym: 'ζ', latex: '\\zeta', name: 'zeta' },
    { sym: 'η', latex: '\\eta', name: 'eta' },
    { sym: 'θ', latex: '\\theta', name: 'theta' },
    { sym: 'λ', latex: '\\lambda', name: 'lambda' },
    { sym: 'μ', latex: '\\mu', name: 'mu' },
    { sym: 'ν', latex: '\\nu', name: 'nu' },
    { sym: 'π', latex: '\\pi', name: 'pi' },
    { sym: 'ρ', latex: '\\rho', name: 'rho' },
    { sym: 'σ', latex: '\\sigma', name: 'sigma' },
    { sym: 'τ', latex: '\\tau', name: 'tau' },
    { sym: 'φ', latex: '\\phi', name: 'phi' },
    { sym: 'ψ', latex: '\\psi', name: 'psi' },
    { sym: 'ω', latex: '\\omega', name: 'omega' },
    { sym: 'Δ', latex: '\\Delta', name: 'Delta' },
    { sym: 'Γ', latex: '\\Gamma', name: 'Gamma' },
    { sym: 'Λ', latex: '\\Lambda', name: 'Lambda' },
    { sym: 'Σ', latex: '\\Sigma', name: 'Sigma' },
    { sym: 'Φ', latex: '\\Phi', name: 'Phi' },
    { sym: 'Ω', latex: '\\Omega', name: 'Omega' },
  ],
  'Operators': [
    { sym: '∫', latex: '\\int', name: 'integral' },
    { sym: '∬', latex: '\\iint', name: 'double integral' },
    { sym: '∑', latex: '\\sum', name: 'sum' },
    { sym: '∏', latex: '\\prod', name: 'product' },
    { sym: '∂', latex: '\\partial', name: 'partial' },
    { sym: '∇', latex: '\\nabla', name: 'nabla' },
    { sym: '√', latex: '\\sqrt{}', name: 'sqrt' },
    { sym: '∞', latex: '\\infty', name: 'infinity' },
    { sym: '±', latex: '\\pm', name: 'plus-minus' },
    { sym: '×', latex: '\\times', name: 'times' },
    { sym: '÷', latex: '\\div', name: 'div' },
    { sym: '·', latex: '\\cdot', name: 'cdot' },
    { sym: '∘', latex: '\\circ', name: 'circ' },
    { sym: '⊕', latex: '\\oplus', name: 'oplus' },
    { sym: '⊗', latex: '\\otimes', name: 'otimes' },
    { sym: '∝', latex: '\\propto', name: 'propto' },
  ],
  'Relations': [
    { sym: '≈', latex: '\\approx', name: 'approx' },
    { sym: '≠', latex: '\\neq', name: 'neq' },
    { sym: '≤', latex: '\\leq', name: 'leq' },
    { sym: '≥', latex: '\\geq', name: 'geq' },
    { sym: '≪', latex: '\\ll', name: 'll' },
    { sym: '≫', latex: '\\gg', name: 'gg' },
    { sym: '∼', latex: '\\sim', name: 'sim' },
    { sym: '≡', latex: '\\equiv', name: 'equiv' },
    { sym: '∈', latex: '\\in', name: 'in' },
    { sym: '∉', latex: '\\notin', name: 'notin' },
    { sym: '⊂', latex: '\\subset', name: 'subset' },
    { sym: '⊃', latex: '\\supset', name: 'supset' },
    { sym: '⊆', latex: '\\subseteq', name: 'subseteq' },
    { sym: '∪', latex: '\\cup', name: 'cup' },
    { sym: '∩', latex: '\\cap', name: 'cap' },
    { sym: '∅', latex: '\\emptyset', name: 'emptyset' },
  ],
  'Arrows': [
    { sym: '→', latex: '\\to', name: 'to' },
    { sym: '←', latex: '\\leftarrow', name: 'leftarrow' },
    { sym: '↔', latex: '\\leftrightarrow', name: 'leftrightarrow' },
    { sym: '⇒', latex: '\\Rightarrow', name: 'Rightarrow' },
    { sym: '⇐', latex: '\\Leftarrow', name: 'Leftarrow' },
    { sym: '⟺', latex: '\\iff', name: 'iff' },
    { sym: '↦', latex: '\\mapsto', name: 'mapsto' },
    { sym: '↑', latex: '\\uparrow', name: 'uparrow' },
    { sym: '↓', latex: '\\downarrow', name: 'downarrow' },
  ],
  'Templates': [
    { sym: 'a/b', latex: '\\frac{a}{b}', name: 'fraction' },
    { sym: 'xⁿ', latex: 'x^{n}', name: 'power' },
    { sym: 'xᵢ', latex: 'x_{i}', name: 'subscript' },
    { sym: '√x', latex: '\\sqrt{x}', name: 'sqrt x' },
    { sym: 'ⁿ√x', latex: '\\sqrt[n]{x}', name: 'nth root' },
    { sym: '∫dx', latex: '\\int_{a}^{b} f(x)\\,dx', name: 'definite integral' },
    { sym: 'lim', latex: '\\lim_{x \\to \\infty}', name: 'limit' },
    { sym: '∑n', latex: '\\sum_{i=1}^{n} a_i', name: 'sum with limits' },
    { sym: 'mat', latex: '\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}', name: 'matrix 2x2' },
    { sym: '|x|', latex: '\\left| x \\right|', name: 'absolute value' },
    { sym: '‖x‖', latex: '\\left\\| x \\right\\|', name: 'norm' },
    { sym: '⟨x⟩', latex: '\\langle x \\rangle', name: 'angle brackets' },
  ],
};

// ---------- EQUATION TEMPLATES ----------
export const EQUATION_TEMPLATES = [
  { label: "Einstein's Energy", latex: 'E = mc^2', type: 'inline' as const },
  { label: "Euler's Identity", latex: 'e^{i\\pi} + 1 = 0', type: 'inline' as const },
  { label: "Pythagorean Theorem", latex: 'a^2 + b^2 = c^2', type: 'inline' as const },
  { label: "Quadratic Formula", latex: 'x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}', type: 'block' as const },
  { label: "Gaussian Integral", latex: '\\int_{-\\infty}^{\\infty} e^{-x^2}\\,dx = \\sqrt{\\pi}', type: 'block' as const },
  { label: "Maxwell's Equation", latex: '\\nabla \\times \\mathbf{B} = \\mu_0\\mathbf{J} + \\mu_0\\varepsilon_0\\frac{\\partial \\mathbf{E}}{\\partial t}', type: 'block' as const },
  { label: "Taylor Series", latex: 'f(x) = \\sum_{n=0}^{\\infty} \\frac{f^{(n)}(a)}{n!}(x-a)^n', type: 'block' as const },
];

// ---------- SLASH COMMANDS ----------
export const SLASH_COMMANDS = [
  { id: 'h1', label: 'Heading 1', desc: 'Large heading', icon: <Heading1 className="w-4 h-4" /> },
  { id: 'h2', label: 'Heading 2', desc: 'Medium heading', icon: <Heading2 className="w-4 h-4" /> },
  { id: 'h3', label: 'Heading 3', desc: 'Small heading', icon: <Heading3 className="w-4 h-4" /> },
  { id: 'bullet', label: 'Bullet list', desc: 'Unordered list', icon: <List className="w-4 h-4" /> },
  { id: 'ordered', label: 'Ordered list', desc: 'Numbered list', icon: <ListOrdered className="w-4 h-4" /> },
  { id: 'task', label: 'Task list', desc: 'Todo checklist', icon: <ListTodo className="w-4 h-4" /> },
  { id: 'quote', label: 'Quote', desc: 'Blockquote', icon: <Quote className="w-4 h-4" /> },
  { id: 'code', label: 'Code block', desc: 'Code snippet', icon: <Code className="w-4 h-4" /> },
  { id: 'table', label: 'Table', desc: 'Insert table', icon: <TableIcon className="w-4 h-4" /> },
  { id: 'todo', label: 'TODO', desc: 'Insert a TODO placeholder', icon: <CheckCircle2 className="w-4 h-4" /> },
  { id: 'math', label: 'Equation', desc: 'Insert inline or block math', icon: <Sigma className="w-4 h-4" /> },
  { id: 'block-math', label: 'Block Equation', desc: 'Displayed equation on own line', icon: <Sigma className="w-4 h-4" /> },
  { id: 'hr', label: 'Divider', desc: 'Horizontal line', icon: <div className="w-4 h-4 border-t-2 border-current" /> },
];

// ---------- MOCK CROSS REFERENCES ----------
export const MOCK_CROSS_REFS = [
  { id: 'fig-1', label: 'Figure 1', type: 'figure' },
  { id: 'fig-2', label: 'Figure 2', type: 'figure' },
  { id: 'tab-1', label: 'Table 1', type: 'table' },
  { id: 'tab-2', label: 'Table 2', type: 'table' },
  { id: 'eq-1', label: 'Equation 1', type: 'equation' },
  { id: 'eq-2', label: 'Equation 2', type: 'equation' },
  { id: 'sec-1', label: 'Section 1: Introduction', type: 'section' },
  { id: 'sec-2', label: 'Section 2: Methods', type: 'section' },
];